export const ERROR_DISPATCH = "ERROR_DISPATCH";
export const AUTH_DISPATCH = "AUTH_DISPATCH";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const ADD_EXPERINCE = "ADD_EXPERINCE";
